version: '3.8'

services:
  mysql:
    # 使用官方 MySQL 镜像，推荐指定小版本以保证稳定
    image: mysql:8.0.39

    # 容器名称
    container_name: mysql

    # 端口映射：宿主机:容器
    # 3306 是 MySQL 默认端口
    ports:
      - "3306:3306"

    # 环境变量 - 这是配置 MySQL 的主要方式
    environment:
      # 必须设置：root 用户的密码
      MYSQL_ROOT_PASSWORD: root
      
      # (可选) 设置默认创建的数据库名称
      MYSQL_DATABASE: pubchat
      
      # (可选) 设置默认创建的用户名和密码
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: myuser_password
      
      # (可选) 指定默认字符集和排序规则，推荐使用 utf8mb4
      MYSQL_INITDB_SKIP_TZINFO: 1  # 跳过时区信息导入，加快初始化
      TZ: Asia/Shanghai             # 设置容器时区

    # 重启策略：除非被手动停止，否则总是重启
    restart: unless-stopped

    # 数据持久化 - ⚠️ 非常重要！
    # 将 MySQL 的数据目录挂载到宿主机
    volumes:
      - mysql_data:/var/lib/mysql    # 数据库文件
      - ./mysql/conf.d:/etc/mysql/conf.d:ro # (可选) 自定义配置文件目录
      - ./mysql/init:/docker-entrypoint-initdb.d:ro # (可选) 初始化 SQL 脚本

    # 资源限制 (可选，根据服务器配置调整)
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #       cpus: '1.0'

# 定义命名卷
volumes:
  mysql_data:
    # driver: local
    # 可以添加 driver_opts 进行更高级的配置
