version: '3.8'

services:
  redis:
    # 使用官方 Redis 镜像，推荐指定版本以保证稳定
    image: redis:7.2.5

    # 容器名称
    container_name: redis

    # 端口映射：宿主机:容器
    # 6379 是 Redis 默认端口
    ports:
      - "6379:6379"

    # 命令行参数（可选）
    # 如果使用自定义配置文件，则不需要在这里传参
    # command: redis-server --appendonly yes --requirepass yourpassword

    # 环境变量
    environment:
      # (可选) 设置 Redis 密码
      # 注意：Redis 官方镜像不直接通过环境变量设置密码
      # 密码需要在配置文件中设置，见下方 custom.conf 示例
      REDIS_PASSWORD: 123456a?

    # 重启策略：除非被手动停止，否则总是重启
    restart: unless-stopped

