truncate table food;
truncate table tag;
truncate table food_tag;

insert into food values (1, '黄焖鸡米饭', 0);
insert into food values (2, '炒饭', 0);
insert into food values (3, '排骨饭', 0);
insert into food values (4, '盖浇饭', 0);
insert into food values (5, '烧腊饭', 0);
insert into food values (6, '咖喱饭', 0);
insert into food values (7, '煲仔饭', 0);
insert into food values (8, '脆皮鸡饭', 0);
insert into food values (9, '烤肉拌饭', 0);
insert into food values (10, '木桶饭', 0);
insert into food values (11, '牛肉饭', 0);
insert into food values (12, '川湘菜', 0);
insert into food values (13, '东北菜', 0);
insert into food values (14, '粤菜', 0);
insert into food values (15, '云南菜', 0);
insert into food values (16, '江浙菜', 0);
insert into food values (17, '鲁菜', 0);
insert into food values (18, '西北菜', 0);
insert into food values (19, '新疆菜', 0);
insert into food values (20, '北京菜', 0);
insert into food values (21, '本帮菜', 0);
insert into food values (22, '海鲜', 0);
insert into food values (23, '日本料理', 0);
insert into food values (24, '日式简餐', 0);
insert into food values (25, '日式烧烤', 0);
insert into food values (26, '刺身寿司', 0);
insert into food values (27, '马来西亚菜', 0);
insert into food values (28, '越南菜', 0);
insert into food values (29, '新加坡菜', 0);
insert into food values (30, '泰国菜', 0);
insert into food values (31, '印度菜', 0);
insert into food values (32, '意大利菜', 0);
insert into food values (33, '法国菜', 0);
insert into food values (34, '西班牙菜', 0);
insert into food values (35, '墨西哥菜', 0);
insert into food values (36, '中东中亚菜', 0);
insert into food values (37, '韩式料理', 0);
insert into food values (38, '韩式烤肉', 0);
insert into food values (39, '蒸鸡滋补鸡', 0);
insert into tag values (1, '美味饭菜');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 39 and t.id = 1;

insert into food values (40, '汉堡薯条', 0);
insert into food values (41, '披萨意面', 0);
insert into food values (42, '牛排', 0);
insert into food values (43, '三明治', 0);
insert into food values (44, '沙拉轻食', 0);
insert into food values (45, '奶茶果汁', 0);
insert into tag value (2, '汉堡披萨');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 45 and f.id >= 40 and t.id = 2;

insert into food values (46, '酸辣粉', 0);
insert into food values (47, '螺蛳粉', 0);
insert into food values (48, '米粉米线', 0);
insert into food values (49, '肠粉', 0);
insert into food values (50, '热干面', 0);
insert into food values (51, '重庆小面', 0);
insert into food values (52, '兰州拉面', 0);
insert into food values (53, '凉皮凉粉', 0);
insert into food values (54, '粉丝汤', 0);
insert into food values (55, '胡辣汤', 0);
insert into food values (56, '牛肉汤', 0);
insert into food values (57, '羊肉汤', 0);
insert into food values (58, '沙茶面', 0);
insert into food values (59, '北京炸酱面', 0);
insert into food values (60, '瓦灌汤', 0);
insert into food values (61, '花甲粉', 0);
insert into food values (62, '烤冷面', 0);
insert into tag value (3, '米粉面汤');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 62 and f.id >= 46 and t.id = 3;

insert into food values (63, '烧烤', 0);
insert into food values (64, '小龙虾', 0);
insert into tag value (4, '龙虾烧烤');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 64 and f.id >= 63 and t.id = 4;

insert into food values (65, '烧饼馅饼', 0);
insert into food values (66, '煎饼', 0);
insert into food values (67, '葱油饼', 0);
insert into food values (68, '水饺', 0);
insert into food values (69, '生煎', 0);
insert into food values (70, '包子汤包', 0);
insert into food values (71, '豆浆油条', 0);
insert into food values (72, '驴肉火烧', 0);
insert into food values (73, '泡馍', 0);
insert into tag value (5, '粥食面点');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 73 and f.id >= 65 and t.id = 5;

insert into food values (74, '贵州菜', 0);
insert into food values (109, '徽菜', 0);
insert into food values (75, '台湾菜', 0);
insert into food values (76, '江西菜', 0);
insert into food values (77, '闽菜', 0);
insert into food values (78, '港菜', 0);
insert into food values (79, '湖北菜', 0);
insert into food values (80, '淮扬菜', 0);
insert into food values (81, '河南菜', 0);
insert into food values (82, '农家菜', 0);
insert into tag value (6, '地方菜');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 82 and f.id >= 74 and t.id = 6;
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 21 and f.id >= 12 and t.id = 6;
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id = 109 and t.id = 6;

insert into food values (83, '章鱼小丸子', 0);
insert into food values (84, '炸鸡炸串', 0);
insert into food values (85, '钵钵鸡', 0);
insert into food values (86, '鸡架', 0);
insert into food values (87, '卤煮', 0);
insert into tag value (7, '特色小吃');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 87 and f.id >= 83 and t.id = 7;
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id in (46, 47, 48, 49, 50, 51, 53, 61, 62) and t.id = 7;

insert into food values (88, '小火锅', 0);
insert into food values (89, '羊蝎子', 0);
insert into food values (90, '川渝火锅', 0);
insert into food values (91, '闷锅', 0);
insert into food values (92, '港式火锅', 0);
insert into food values (93, '铜锅涮肉', 0);
insert into food values (94, '麻辣香锅', 0);
insert into food values (95, '干锅', 0);
insert into food values (96, '鸡公煲', 0);
insert into food values (97, '砂锅', 0);
insert into food values (98, '烤鱼', 0);
insert into food values (99, '麻辣烫', 0);
insert into tag value (8, '麻辣烫香锅');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 99 and f.id >= 88 and t.id = 7;


insert into food values (100, '卤味熟食', 0);
insert into food values (101, '粉丝汤', 0);

insert into food values (102, '咖啡', 0);
insert into food values (103, '甜品', 0);
insert into food values (104, '面包', 0);
insert into food values (105, '泡面', 0);
insert into food values (106, '蛋糕', 0);
insert into food values (107, '冰淇淋', 0);
insert into food values (108, '水果捞', 0);
insert into tag value (9, '咖啡甜品');
insert into food_tag select uuid_short(), f.id, t.id from food f, tag t where f.id <= 108 and f.id >= 102 and t.id = 9;
